"""empty message

Revision ID: 35295405bcec
Revises: faa7aef47179
Create Date: 2025-08-27 15:24:05.267205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35295405bcec'
down_revision = 'faa7aef47179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('meeting_url', sa.String(length=500), nullable=False),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_column('lessons_count')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lessons_count', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    op.drop_table('live_class')
    # ### end Alembic commands ###
