"""empty message

Revision ID: 3e3992c0c5b0
Revises: bd6da39ab3f7
Create Date: 2025-11-13 03:35:45.195324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e3992c0c5b0'
down_revision = 'bd6da39ab3f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('live_class')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_class',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('meeting_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('recording_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('schedule_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('live_class_course_id_fkey')),
    sa.ForeignKeyConstraint(['schedule_id'], ['course_schedule.id'], name=op.f('live_class_schedule_id_fkey')),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], name=op.f('live_class_teacher_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('live_class_pkey'))
    )
    # ### end Alembic commands ###
