"""empty message

Revision ID: 436f4d48b46e
Revises: 8ebc4689ea1f
Create Date: 2025-07-09 15:13:18.175959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436f4d48b46e'
down_revision = '8ebc4689ea1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
