"""empty message

Revision ID: 4646ccc713c7
Revises: aef9dbeb21e4
Create Date: 2025-11-13 13:31:28.473192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4646ccc713c7'
down_revision = 'aef9dbeb21e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_course', schema=None) as batch_op:
        batch_op.drop_column('progress')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
