"""empty message

Revision ID: 46996b06cc0a
Revises: ffbff3bb6484
Create Date: 2025-10-24 12:11:02.762106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46996b06cc0a'
down_revision = 'ffbff3bb6484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.drop_column('is_published')

    # ### end Alembic commands ###
