"""empty message

Revision ID: 5037a2ac1016
Revises: 4061dfeaa6ea
Create Date: 2025-10-21 18:57:45.811326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5037a2ac1016'
down_revision = '4061dfeaa6ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.create_foreign_key(None, 'course_schedule', ['schedule_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_class', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('title')
        batch_op.drop_column('schedule_id')

    # ### end Alembic commands ###
