"""empty message

Revision ID: 52e6e697f4e9
Revises: 26f1e546f701
Create Date: 2025-08-12 16:51:55.508065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e6e697f4e9'
down_revision = '26f1e546f701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('block_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('block_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_blocked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('blocked_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('blocked_until')
        batch_op.drop_column('last_blocked_at')
        batch_op.drop_column('block_count')
        batch_op.drop_column('block_reason')
        batch_op.drop_column('is_blocked')

    # ### end Alembic commands ###
