"""empty message

Revision ID: 668dada917d9
Revises: e26bdbed1c55
Create Date: 2025-10-28 19:17:59.725229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668dada917d9'
down_revision = 'e26bdbed1c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###
