"""Add country and id_number to User

Revision ID: 67632262893c
Revises: f4ddf3595c9f
Create Date: 2025-07-08 16:07:57.933008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '67632262893c'
down_revision = 'f4ddf3595c9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Primero agregamos las columnas como NULLABLE
        batch_op.add_column(sa.Column('country', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('id_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
    
    # Asignamos valores por defecto a registros existentes
    op.execute(text("UPDATE \"user\" SET country = 'US' WHERE country IS NULL"))
    op.execute(text("UPDATE \"user\" SET id_number = 'pending' WHERE id_number IS NULL"))
    op.execute(text("UPDATE \"user\" SET created_at = NOW() WHERE created_at IS NULL"))
    
    # Finalmente cambiamos a NOT NULL
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('country', nullable=False)
        batch_op.alter_column('id_number', nullable=False)
        batch_op.alter_column('created_at', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('id_number')
        batch_op.drop_column('country')
    # ### end Alembic commands ###