"""empty message

Revision ID: 6f99ce59c505
Revises: 3f3c36b07d52
Create Date: 2025-09-23 20:29:09.561836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f99ce59c505'
down_revision = '3f3c36b07d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_duration', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('access_duration')

    # ### end Alembic commands ###
