"""empty message

Revision ID: 73188a0c62ab
Revises: 3895009826af
Create Date: 2025-11-13 15:29:59.674558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73188a0c62ab'
down_revision = '3895009826af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'course_schedule', ['schedule_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('schedule_id')

    # ### end Alembic commands ###
