"""empty message

Revision ID: 7ad82885d3f9
Revises: b8a8ef862040
Create Date: 2025-07-07 13:54:19.582669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad82885d3f9'
down_revision = 'b8a8ef862040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocked_token_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocked_token_list', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
