"""empty message

Revision ID: 9cb4bf076f8a
Revises: e36f17463815
Create Date: 2025-07-09 18:04:32.439121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb4bf076f8a'
down_revision = 'e36f17463815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocked_token_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('blocked_token_list', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
