"""empty message

Revision ID: a1eec18ae746
Revises: 58933b5f118b
Create Date: 2025-09-17 12:58:06.336089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1eec18ae746'
down_revision = '58933b5f118b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('certificate_available')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificate_available', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
