"""empty message

Revision ID: ab0afa18056a
Revises: cc4621f362f9
Create Date: 2025-09-17 14:39:42.907360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab0afa18056a'
down_revision = 'cc4621f362f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('is_preview')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_preview', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
