"""empty message

Revision ID: b580d3a6cc38
Revises: 73188a0c62ab
Create Date: 2025-11-13 16:46:01.312598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b580d3a6cc38'
down_revision = '73188a0c62ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['teacher_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_schedule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###
