"""empty message

Revision ID: cc4621f362f9
Revises: e791a7aa6181
Create Date: 2025-09-17 14:38:15.053179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4621f362f9'
down_revision = 'e791a7aa6181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
