"""empty message

Revision ID: d34ba02aa8b3
Revises: f7aef7de3e47
Create Date: 2025-09-19 13:56:39.230858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd34ba02aa8b3'
down_revision = 'f7aef7de3e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.String(length=100), nullable=True))

    with op.batch_alter_table('live_class', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
