"""empty message

Revision ID: e791a7aa6181
Revises: a1eec18ae746
Create Date: 2025-09-17 14:32:06.771985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e791a7aa6181'
down_revision = 'a1eec18ae746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('alt_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alt_text', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
