"""empty message

Revision ID: f0d9a53ce171
Revises: 9657bf571ea4
Create Date: 2025-10-15 21:01:02.307096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f0d9a53ce171'
down_revision = '9657bf571ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('live_class_start_time')
        batch_op.drop_column('live_class_end_time')
        batch_op.drop_column('live_class_days')
        batch_op.drop_column('live_class_timezone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('live_class_timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('live_class_days', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('live_class_end_time', postgresql.TIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('live_class_start_time', postgresql.TIME(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
