"""empty message

Revision ID: f7aef7de3e47
Revises: ab0afa18056a
Create Date: 2025-09-17 17:14:23.002480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7aef7de3e47'
down_revision = 'ab0afa18056a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_live_classes', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_recorded_videos', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('live_class_days', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('live_class_start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('live_class_end_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('live_class_timezone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('live_class_timezone')
        batch_op.drop_column('live_class_end_time')
        batch_op.drop_column('live_class_start_time')
        batch_op.drop_column('live_class_days')
        batch_op.drop_column('has_recorded_videos')
        batch_op.drop_column('has_live_classes')

    # ### end Alembic commands ###
