// coursesData.js
import image from "../../img/noImage.jpg";

export const courses = [
  {
    id: 1,
    slug: "advanced-math",
    image: image,
    alt: "Advanced Mathematics",
    title: "Advanced Mathematics: Calculus & Linear Algebra",
    description:
      "Explore the depths of calculus and linear algebra in this advanced course designed for aspiring mathematicians and engineers.",
    instructor: "Dr. Sarah Johnson",
    instructorImage: "https://randomuser.me/api/portraits/women/44.jpg",
    instructorBio:
      "Professor of Mathematics with 15 years of teaching experience at top universities.",
    rating: 4.7,
    reviews: 1248,
    lessons: 42,
    students: 10500,
    level: "Intermediate",
    price: 89.99,
    discountPrice: 59.99,
    language: "English",
    certificate: true,
    lastUpdated: "June 2023",
    // Nueva información de horario y modalidad
    schedule: {
      days: ["Lunes", "Miércoles"],
      time: "7:00 PM - 9:00 PM",
      timezone: "GMT-5",
    },
    liveClasses: true,
    recordedVideos: true,
    whatYouLearn: [
      "Master fundamental concepts of calculus and linear algebra",
      "Solve complex mathematical problems with confidence",
      "Apply mathematical principles to real-world scenarios",
      "Develop critical thinking and analytical skills",
      "Prepare for advanced studies in mathematics or engineering",
    ],
    curriculum: [
      {
        module: "Module 1",
        title: "Introduction to Calculus",
        lessons: 5,
      },
      {
        module: "Module 2",
        title: "Limits and Continuity",
        lessons: 6,
      },
      {
        module: "Module 3",
        title: "Differentiation",
        lessons: 7,
      },
      {
        module: "Module 4",
        title: "Applications of Derivatives",
        lessons: 6,
      },
      {
        module: "Module 5",
        title: "Integration",
        lessons: 8,
      },
      {
        module: "Module 6",
        title: "Fundamentals of Linear Algebra",
        lessons: 5,
      },
      {
        module: "Module 7",
        title: "Matrix Operations",
        lessons: 5,
      },
    ],
    requirements: [
      "Basic algebra knowledge",
      "Familiarity with mathematical concepts",
      "Scientific calculator (recommended)",
      "Dedication to complete exercises",
    ],
  },
  {
    id: 2,
    slug: "art-fundamentals",
    image: image,
    alt: "Art Fundamentals",
    title: "Fundamentals of Fine Arts & Creative Design",
    description:
      "Dive into the world of fine arts and creative design, mastering the essential techniques and concepts that form the foundation of artistic expression.",
    instructor: "Prof. Michael Chen",
    instructorImage: "https://randomuser.me/api/portraits/men/32.jpg",
    instructorBio:
      "Professional artist and designer with 10+ years of experience in the creative industry.",
    rating: 4.8,
    reviews: 892,
    lessons: 36,
    students: 8700,
    level: "Beginner",
    price: 79.99,
    discountPrice: 49.99,
    language: "English",
    certificate: true,
    lastUpdated: "May 2023",
    schedule: {
      days: ["Lunes", "Miércoles"],
      time: "7:00 PM - 9:00 PM",
      timezone: "GMT-5",
    },
    liveClasses: true,
    recordedVideos: true,
    whatYouLearn: [
      "Fundamentals of drawing and composition",
      "Color theory and application",
      "Creative design principles",
      "Various artistic techniques",
      "Developing your unique artistic style",
    ],
    curriculum: [
      {
        module: "Module 1",
        title: "Drawing Fundamentals",
      },
      {
        module: "Module 2",
        title: "Perspective and Composition",
      },
      {
        module: "Module 3",
        title: "Color Theory",
      },
      {
        module: "Module 4",
        title: "Creative Design Principles",
      },
    ],
    requirements: [
      "Basic drawing materials (pencils, paper)",
      "Openness to creative exploration",
      "Willingness to practice regularly",
    ],
  },
  {
    id: 3,
    slug: "business-management",
    image: image,
    alt: "Business Management",
    title: "Modern Business Management & Entrepreneurship",
    description:
      "Learn the principles of modern business management and entrepreneurship, equipping yourself with the skills to succeed in today's dynamic business environment.",
    instructor: "Dr. Emily Wilson",
    instructorImage: "https://randomuser.me/api/portraits/women/65.jpg",
    instructorBio:
      "Business consultant and entrepreneur with successful startups in multiple industries.",
    rating: 4.6,
    reviews: 1103,
    lessons: 48,
    students: 12500,
    level: "All Levels",
    price: 99.99,
    discountPrice: 69.99,
    language: "English",
    certificate: true,
    lastUpdated: "July 2023",
    whatYouLearn: [
      "Business planning and strategy",
      "Financial management basics",
      "Marketing and sales techniques",
      "Leadership and team management",
      "Entrepreneurial mindset development",
    ],
    curriculum: [
      {
        module: "Module 1",
        title: "Business Fundamentals",
      },
      {
        module: "Module 2",
        title: "Market Analysis",
      },
      {
        module: "Module 3",
        title: "Financial Management",
      },
      {
        module: "Module 4",
        title: "Leadership Principles",
      },
    ],
    requirements: [
      "Interest in business development",
      "Basic math skills",
      "Notebook for planning exercises",
    ],
  },
  {
    id: 4,
    slug: "web-development",
    image: image,
    alt: "Programming Course",
    title: "Full-Stack Web Development Bootcamp",
    description:
      "Become a full-stack web developer with this comprehensive bootcamp, covering everything from front-end design to back-end programming.",
    instructor: "Alex Johnson",
    instructorImage: "https://randomuser.me/api/portraits/men/76.jpg",
    instructorBio:
      "Senior developer with 12 years of experience in web technologies.",
    rating: 4.9,
    reviews: 2156,
    lessons: 120,
    students: 18500,
    level: "Beginner to Advanced",
    price: 199.99,
    discountPrice: 149.99,
    language: "English",
    certificate: true,
    lastUpdated: "August 2023",
    whatYouLearn: [
      "HTML, CSS and modern JavaScript",
      "Front-end frameworks (React)",
      "Back-end development (Node.js)",
      "Database management",
      "Deployment and DevOps basics",
    ],
    curriculum: [
      {
        module: "Module 1",
        title: "HTML & CSS Fundamentals",
      },
      {
        module: "Module 2",
        title: "JavaScript Mastery",
      },
      {
        module: "Module 3",
        title: "Front-end with React",
      },
      {
        module: "Module 4",
        title: "Back-end Development",
      },
    ],
    requirements: [
      "Basic computer skills",
      "Dedication to code daily",
      "Modern computer (Windows/Mac/Linux)",
    ],
  },
  {
    id: 5,
    slug: "statistics-data-analysis",
    image: image,
    alt: "Statistics Course",
    title: "Applied Statistics & Data Analysis",
    description:
      "Master the art of data analysis with applied statistics, learning how to interpret and visualize data effectively.",
    instructor: "Dr. Robert Kim",
    instructorImage: "https://randomuser.me/api/portraits/men/45.jpg",
    instructorBio:
      "Data scientist with PhD in Statistics and industry experience.",
    rating: 4.5,
    reviews: 876,
    lessons: 50,
    students: 9500,
    level: "Intermediate",
    price: 89.99,
    discountPrice: 59.99,
    language: "English",
    certificate: true,
    lastUpdated: "May 2023",
    whatYouLearn: [
      "Statistical concepts and methods",
      "Data visualization techniques",
      "Hypothesis testing",
      "Regression analysis",
      "Working with statistical software",
    ],
    curriculum: [
      {
        module: "Module 1",
        title: "Descriptive Statistics",
      },
      {
        module: "Module 2",
        title: "Probability Basics",
      },
      {
        module: "Module 3",
        title: "Statistical Inference",
      },
      {
        module: "Module 4",
        title: "Regression Analysis",
      },
    ],
    requirements: [
      "Basic math knowledge",
      "Familiarity with spreadsheets",
      "Statistical software (instructions provided)",
    ],
  },
  {
    id: 6,
    slug: "digital-art-design",
    image: image,
    alt: "Digital Art",
    title: "Digital Illustration & Graphic Design",
    description:
      "Unleash your creativity with digital illustration and graphic design, mastering the tools and techniques to create stunning visual content.",
    instructor: "Lisa Rodriguez",
    instructorImage: "https://randomuser.me/api/portraits/women/28.jpg",
    instructorBio:
      "Professional digital artist and Adobe Certified Instructor.",
    rating: 4.7,
    reviews: 1024,
    lessons: 40,
    students: 11200,
    level: "Beginner to Intermediate",
    price: 84.99,
    discountPrice: 54.99,
    language: "English",
    certificate: true,
    lastUpdated: "April 2023",
    whatYouLearn: [
      "Digital drawing techniques",
      "Graphic design principles",
      "Using design software (Photoshop, Illustrator)",
      "Creating professional artwork",
      "Building a design portfolio",
    ],
    curriculum: [
      {
        module: "Module 1",
        title: "Digital Art Basics",
      },
      {
        module: "Module 2",
        title: "Design Principles",
      },
      {
        module: "Module 3",
        title: "Advanced Techniques",
      },
      {
        module: "Module 4",
        title: "Portfolio Development",
      },
    ],
    requirements: [
      "Graphic tablet (recommended)",
      "Design software (trial versions acceptable)",
      "Creative mindset",
    ],
  },
  {
    id: 7,
    slug: "digital-marketing",
    image: image,
    alt: "Marketing Course",
    title: "Digital Marketing & Social Media Strategy",
    description:
      "Explore the world of digital marketing and social media strategy, learning how to effectively promote brands and engage audiences online.",
    instructor: "David Miller",
    instructorImage: "https://randomuser.me/api/portraits/men/33.jpg",
    instructorBio:
      "Digital marketing expert with Fortune 500 company experience.",
    rating: 4.4,
    reviews: 789,
    lessons: 35,
    students: 8900,
    level: "All Levels",
    price: 79.99,
    discountPrice: 49.99,
    language: "English",
    certificate: true,
    lastUpdated: "June 2023",
    whatYouLearn: [
      "Digital marketing fundamentals",
      "Social media strategy",
      "Content marketing",
      "SEO and SEM basics",
      "Analytics and performance measurement",
    ],
    curriculum: [
      {
        module: "Module 1",
        title: "Marketing Fundamentals",
      },
      {
        module: "Module 2",
        title: "Social Media Strategies",
      },
      {
        module: "Module 3",
        title: "Content Creation",
      },
      {
        module: "Module 4",
        title: "Performance Analysis",
      },
    ],
    requirements: [
      "Basic computer skills",
      "Social media accounts",
      "Interest in marketing",
    ],
  },
  {
    id: 8,
    slug: "mobile-development",
    image: image,
    alt: "Mobile Development",
    title: "Mobile App Development with React Native",
    description:
      "Learn how to build cross-platform mobile applications using React Native, a powerful framework for mobile development.",
    instructor: "Sarah Williams",
    instructorImage: "https://randomuser.me/api/portraits/women/51.jpg",
    instructorBio: "Mobile developer with published apps in app stores.",
    rating: 4.8,
    reviews: 1345,
    lessons: 60,
    students: 10500,
    level: "Intermediate",
    price: 109.99,
    discountPrice: 79.99,
    language: "English",
    certificate: true,
    lastUpdated: "July 2023",
    whatYouLearn: [
      "React Native fundamentals",
      "Building cross-platform apps",
      "State management",
      "API integration",
      "App deployment process",
    ],
    curriculum: [
      {
        module: "Module 1",
        title: "React Native Basics",
      },
      {
        module: "Module 2",
        title: "UI Development",
      },
      {
        module: "Module 3",
        title: "State Management",
      },
      {
        module: "Module 4",
        title: "App Deployment",
      },
    ],
    requirements: [
      "Basic JavaScript knowledge",
      "React basics (helpful but not required)",
      "Android/iOS device for testing",
    ],
  },
  {
    id: 9,
    slug: "data-science",
    image: image,
    alt: "Discrete Mathematics",
    title: "Discrete Mathematics for Computer Science",
    description:
      "Delve into discrete mathematics, a crucial area for computer science, covering topics such as logic, set theory, and graph theory.",
    instructor: "Prof. James Anderson",
    instructorImage: "https://randomuser.me/api/portraits/men/62.jpg",
    instructorBio:
      "Computer science professor with research focus on algorithms.",
    rating: 4.6,
    reviews: 967,
    lessons: 45,
    students: 8700,
    level: "Intermediate",
    price: 94.99,
    discountPrice: 64.99,
    language: "English",
    certificate: true,
    lastUpdated: "May 2023",
    whatYouLearn: [
      "Mathematical logic",
      "Set theory applications",
      "Graph theory basics",
      "Combinatorics",
      "Applications in computer science",
    ],
    curriculum: [
      {
        module: "Module 1",
        title: "Logic and Proofs",
      },
      {
        module: "Module 2",
        title: "Set Theory",
      },
      {
        module: "Module 3",
        title: "Graph Theory",
      },
      {
        module: "Module 4",
        title: "Combinatorics",
      },
    ],
    requirements: [
      "Basic math skills",
      "Logical thinking",
      "Interest in theoretical CS",
    ],
  },
];
